config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)
  resources :stats
  resources :matches
  resources :series
  resources :players
  resources :teams
  resources :users
  resources :serie_stats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#check_user"
  get "probando/home" => "home#home"
  get "login" => "home#login"
  get "dashboard" => "home#dashboard"
  get "points" => "home#points"
  get "semis" => "home#semis"
  get "finals" => "home#finals"
  get "/services/fix_serie_stats" => "home#fix_serie_stats_winner"
end

app/models/user.rb
class User < ApplicationRecord
  # lo distinto con Current es q quiero q sea mayor a 2018
  # para q tome en cuenta los users de antes para adelante
  default_scope { where("created_at > ?", Date.new(2018)) }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :stats
  has_many :serie_stats
  belongs_to :mvp, class_name: "Player", foreign_key: "mvp_id"
  belongs_to :team

  after_create :send_welcome_email

  def send_welcome_email
    ApplicationMailer.welcome_email(self).deliver_now
  end

  def points
    total = serie_points + mvp_points
    total.round(2)
  end

  def serie_points
    serie_stats.map(&:points).sum
  end

  def mvp_points
    the_finals = Serie.the_finals
    if mvp && the_finals &&  mvp == the_finals.mvp
      25
    else
      0
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    name = user_params[:name]

    user = User.find_by(name: name)

    if user
      session[:user_id] = user.id
      redirect_to :dashboard, notice: "Estas logeado"
    else
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          session[:user_id] = @user.id
          format.html { redirect_to :dashboard, notice: "Se creo el usuario #{name}" }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to :dashboard, notice: 'Perfil Guardado!' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :dashboard }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :team_id, :mvp_name)
    end
end

app/views/users/_form.html.erb
<%= form_for(user, html: {class: "form-horizontal"}) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Nickname", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Equipo Favorito", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:team_id, Team.all.map{|t| [t.name, t.id]}, {prompt: "Elegi tu equipo"}, {class: "form-control", disabled: true}) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Finals MVP", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :mvp_name, class: "form-control", disabled: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Guardar', class: "btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<div style="padding: 0 20px">
<h1>Editar Perfil</h1>

<%= render 'form', user: @user %>

<div>
  <%= link_to "Cambiar password", edit_user_registration_path %>
</div>
<div>
  <%= link_to 'Volver', dashboard_path %>
</div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>